# 开发环境配置
server:
  # 端口
  port: 8085

# 日志配置
logging:
  level:
    com.test.rooming: debug
    com.springframework: warn

spring:
  profiles:
    active: dev
  # 服务模块
  devtools:
    # 热部署开关
    restart:
      enabled: true

mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.test.rooming
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      capital-mode: true
  configuration:
    cache-enabled: false
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl